//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassette.Stylesheets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cassette.Stylesheets.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(definition){if(typeof define==&quot;function&quot;){define(definition)}else if(typeof YUI==&quot;function&quot;){YUI.add(&quot;es5&quot;,definition)}else{definition()}})(function(){function Empty(){}if(!Function.prototype.bind){Function.prototype.bind=function bind(that){var target=this;if(typeof target!=&quot;function&quot;){throw new TypeError(&quot;Function.prototype.bind called on incompatible &quot;+target)}var args=_Array_slice_.call(arguments,1);var bound=function(){if(this instanceof bound){var result=target.apply(this,args.concat(_Array_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string es5_shim_min {
            get {
                return ResourceManager.GetString("es5_shim_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * LESS - Leaner CSS v1.4.1
        /// * http://lesscss.org
        /// *
        /// * Copyright (c) 2009-2013, Alexis Sellier
        /// * Licensed under the Apache 2.0 License.
        /// *
        /// * @licence
        /// */(function(e,t){function n(t){return e.less[t.split(&quot;/&quot;)[1]]}function f(){r.env===&quot;development&quot;?(r.optimization=0,r.watchTimer=setInterval(function(){r.watchMode&amp;&amp;g(function(e,t,n,i,s){e?k(e,i.href):t&amp;&amp;S(t.toCSS(r),i,s.lastModified)})},r.poll)):r.optimization=3}function m(){var e=document.getElementsByTagName(&quot;style&quot;);for(var t=0;t&lt;e.length;t++)if(e[t] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string less_1_4_1_min {
            get {
                return ResourceManager.GetString("less_1_4_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///Less.js compiler for Windows Script Host
        ///http://blog.dotsmart.net/
        ///Modified by Van Kichline (vank), Microsoft. 10/2012:
        ///Emit errors in imported files.
        ///
        ///Copyright (c) 2010, Duncan Smart
        ///Licensed under the Apache 2.0 License.
        ///--&gt;
        ///&lt;job&gt;
        ///    &lt;script language=&quot;jscript&quot;&gt;
        ///        // Stub out globals
        ///        var window = this;
        ///        var location = window.location = {
        ///            port: 0,
        ///            href: &apos;&apos;,
        ///            protocol: &apos;http:&apos;,      // vank: added to support development env setting
        ///            ho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lessc {
            get {
                return ResourceManager.GetString("lessc", resourceCulture);
            }
        }
    }
}
