namespace Cassette
{
    /// <summary>
    /// Modifies the URLs generated by Cassette.
    /// </summary>
    public interface IUrlModifier
    {
        /// <summary>
        /// Modifies a URL.
        /// </summary>
        /// <param name="url">The URL to modify.</param>
        /// <returns>The modified URL.</returns>
        string PreCacheModify(string url);

        /// <summary>
        /// Modifies a URL only during rendering for a page to ensure that specific url is not cached
        /// </summary>
        /// <param name="url">The URL to modify.</param>
        /// <returns>The modified URL.</returns>
        string PostCacheModify(string url);
    }
}
