//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassette.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cassette.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * CoffeeScript Compiler v1.1.2
        /// * http://coffeescript.org
        /// *
        /// * Copyright 2011, Jeremy Ashkenas
        /// * Released under the MIT License
        /// */
        ///this.CoffeeScript=function(){function require(a){return require[a]}require[&quot;./helpers&quot;]=new function(){var a=this;(function(){var b,c;a.starts=function(a,b,c){return b===a.substr(c,b.length)},a.ends=function(a,b,c){var d;d=b.length;return b===a.substr(a.length-d-(c||0),d)},a.compact=function(a){var b,c,d,e;e=[];for(c=0,d=a.length;c&lt;d;c++)b=a[c],b&amp;&amp;e.push(b);return e},a.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string coffeescript {
            get {
                return ResourceManager.GetString("coffeescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// *  Copyright 2011 Twitter, Inc.
        /// *  Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// *  you may not use this file except in compliance with the License.
        /// *  You may obtain a copy of the License at
        /// *
        /// *  http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// *  Unless required by applicable law or agreed to in writing, software
        /// *  distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        /// *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        /// *  See the License for [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hogan {
            get {
                return ResourceManager.GetString("hogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This code was butchered out of https://github.com/jquery/jquery-tmpl
        ///// It provides just enough to build HTML templates into a JavaScript function.
        ///
        ////*!
        ///* jQuery Templates Plugin 1.0.0pre
        ///* http://github.com/jquery/jquery-tmpl
        ///* Requires jQuery 1.4.2
        ///*
        ///* Copyright Software Freedom Conservancy, Inc.
        ///* Dual licensed under the MIT or GPL Version 2 licenses.
        ///* http://jquery.org/license
        ///*/
        ///var tmplTags = {
        ///    &quot;tmpl&quot;: {
        ///        _default: { $2: &quot;null&quot; },
        ///        open: &quot;if($notnull_1){__=__.conca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryTmplCompiler {
            get {
                return ResourceManager.GetString("jqueryTmplCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This code was butchered out of https://github.com/SteveSanderson/knockout
        ///// It provides the rewriteTemplate function which is need to rewrite any data-bind attributes
        ///// in an HTML template before compiling it into JavaScript.
        ///
        ///// Knockout JavaScript library v1.2
        ///// (c) Steven Sanderson - http://knockoutjs.com/
        ///// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///var ko = {};
        ///var stringTrimRegex = /^(\s|\u00A0)+|(\s|\u00A0)+$/g;
        ///
        ///// Extend the default tmplTags object (from jque [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jqueryTmplKnockout {
            get {
                return ResourceManager.GetString("jqueryTmplKnockout", resourceCulture);
            }
        }
    }
}
