//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassette.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cassette.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Cassette&lt;/title&gt;
        ///    &lt;link href=&quot;//ajax.googleapis.com/ajax/libs/jqueryui/1.8.15/themes/smoothness/jquery-ui.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot;/&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-size: 62.5%;
        ///        }
        ///        .bundle {
        ///            margin-bottom: 1.5em;
        ///        }
        ///        .bundle &gt; a {
        ///            font-weight: bold;
        ///        }
        ///        .bundle ul {
        ///            margin-top: .5em;
        ///        }
        ///        .bundle ul, .bundle p {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hud {
            get {
                return ResourceManager.GetString("hud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Knockout JavaScript library v1.3.0beta
        ///// (c) Steven Sanderson - http://knockoutjs.com/
        ///// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///
        ///(function(window,undefined){ 
        ///var ko = window[&quot;ko&quot;] = {};
        ///// Google Closure Compiler helpers (used only to make the minified file smaller)
        ///ko.exportSymbol = function(publicPath, object) {
        ///	var tokens = publicPath.split(&quot;.&quot;);
        ///	var target = window;
        ///	for (var i = 0; i &lt; tokens.length - 1; i++)
        ///		target = target[tokens[i]];
        ///	target[tokens[to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string knockout {
            get {
                return ResourceManager.GetString("knockout", resourceCulture);
            }
        }
    }
}
